### ISSUE TITLE
Documentation correction

### ISSUE THREAD

**Issue by Naoray** [Laralum/Payments#5]
In the [Payments Documentation](https://laralum.com/docs/Payments/API) is a small spelling mistake.

`Laralum\Payments\Models\Settigns` should be `Laralum\Payments\Models\Settings`

If you would make the docs editing public I could also correct such small issues...

**Comment by ConsoleTVs** [comment]
It's OK, gonna fix it myself. The docs are in a private repo out of github, personal reasons, we want more control over them, sorry for the issue and thanks for pointing it out!

**Comment by ConsoleTVs** [comment]
Fixed :)
